main: keithcod.es.generators.Generators
name: Generators
version: 1.0
authors:
    - xNagisa_
    - Myron-Pigna
description: Create blocks that spawn items
commands:
  gen:
    description: Open the GUI for creating generators
    usage: /gen
    aliases: [generators, generator, gen]
    permission: generator.use
permissions:
    generator.*:
        description: Gives access to all Generator commands
        default: op
        children:
            hearthstone.use: true
    generator.use:
        description: Allow to create new Generators
        default: op